import { Appointment, NotificationLog, BusinessScheduleSettings, SecuritySettings } from '@/types';

/**
 * Base de datos maestra y permanente para Afinaciones de Autor.
 * Incluye el catálogo completo del equipo de trabajo y el ciclo de vida de cotizaciones en todas las etapas.
 */

export const INITIAL_SECURITY_SETTINGS: SecuritySettings = {
  adminPin: '123456',
  technicianPin: '123456',
  staffMembers: [
    {
      id: 'staff-1',
      name: 'Luis Carlos Carranza',
      phone: '3334884592',
      role: 'admin',
      status: 'active',
      pin: '123456',
      createdAt: '2026-08-24T10:00:00.000Z',
    },
    {
      id: 'staff-2',
      name: 'Luis González',
      phone: '3334884592',
      role: 'technician',
      status: 'active',
      pin: '123456',
      createdAt: '2026-08-24T10:00:00.000Z',
    },
    {
      id: 'staff-3',
      name: 'Carlos Carranza',
      phone: '3334884592',
      role: 'technician',
      status: 'active',
      pin: '123456',
      createdAt: '2026-08-24T10:00:00.000Z',
    },
  ],
};

export const INITIAL_SCHEDULE_SETTINGS: BusinessScheduleSettings = {
  workingDays: [
    { dayOfWeek: 1, name: 'Lunes', enabled: true },
    { dayOfWeek: 2, name: 'Martes', enabled: true },
    { dayOfWeek: 3, name: 'Miércoles', enabled: true },
    { dayOfWeek: 4, name: 'Jueves', enabled: true },
    { dayOfWeek: 5, name: 'Viernes', enabled: true },
    { dayOfWeek: 6, name: 'Sábado', enabled: true },
    { dayOfWeek: 0, name: 'Domingo', enabled: true },
  ],
  slots: [
    { id: 'slot-1', slot: '09:00 - 11:30', label: 'Mañana (Recomendado)', active: true },
    { id: 'slot-2', slot: '12:00 - 14:30', label: 'Mediodía', active: true },
    { id: 'slot-3', slot: '15:30 - 18:00', label: 'Tarde', active: true },
    { id: 'slot-4', slot: '18:30 - 20:30', label: 'Vespertino', active: true },
  ],
  blockedDates: [],
};

export const INITIAL_APPOINTMENTS: Appointment[] = [
  // 1. CITA CONFIRMADA / EN RUTA HOY (Emilio González)
  {
    id: 'apt-1787603395427',
    folio: 'ADA-2026-115',
    client: {
      name: 'Emilio González García',
      phone: '3334884592',
      email: 'emilio.gonzalez@gmail.com',
      address: 'Santa Monica 128 Nueva Santa Maria, Guadalajara',
      referenceNotes: 'Portón gris frente al parque',
    },
    vehicle: {
      brand: 'KIA',
      model: 'Soul',
      year: 2023,
      plates: 'DSS-421-5',
      vin: 'KNDJP3A56N7129845',
      engine: '2.0L MPI 4 Cilindros',
      currentKm: 42350,
    },
    packageType: 'mayor',
    serviceDescription: 'Afinación Mayor de Alto Rendimiento a Domicilio',
    selectedOption: 'premium',
    quote: {
      agency: {
        title: 'Opción Agencia (KIA OEM)',
        description: 'Refacciones 100% de concesionaria autorizada KIA.',
        partsBrand: 'Genuino KIA OEM',
        warrantyMonths: 6,
        laborCost: 650,
        partsSubtotal: 2650,
        price: 3300,
        highlights: [
          'Refacciones 100% de concesionaria oficial',
          'Póliza de garantía legal de 6 meses',
          'Inspección y escaneo digital en tu domicilio',
        ],
      },
      premium: {
        title: 'Opción De Autor (Alto Rendimiento)',
        description: 'Refacciones de especificación superior (Motul 8100 100% Sintético, NGK Laser Iridium, Mann Filter Pro).',
        partsBrand: 'Motul 8100 + NGK Laser Iridium + Mann Filter Pro',
        warrantyMonths: 12,
        laborCost: 650,
        partsSubtotal: 3100,
        price: 3750,
        highlights: [
          'Marcas premium de máximo desempeño y durabilidad',
          'Garantía extendida por escrito de 12 meses / 15,000 km',
          'Descarbonización ultrasónica y calibración con escáner OBD-II',
        ],
      },
      itemsChecklist: [
        { name: '4x Bujías NGK Laser Iridium', spec: 'Calibración GAP 0.8mm', includedInAgency: true, includedInPremium: true },
        { name: 'Aceite Motul 8100 100% Sintético 5W-30 (5L)', spec: 'API SP / ILSAC GF-6A', includedInAgency: true, includedInPremium: true },
        { name: 'Filtro de Aceite Mann Filter W712', spec: 'Válvula antidrenaje blindada', includedInAgency: true, includedInPremium: true },
        { name: 'Filtro de Aire Mann Filter C30005', spec: 'Microfiltración de alto flujo', includedInAgency: true, includedInPremium: true },
        { name: 'Filtro de Cabina Mann Filter CUK', spec: 'Carbón activado anti-alérgenos', includedInAgency: true, includedInPremium: true },
        { name: 'Descarbonizado de Inyectores & Cuerpo TPS', spec: 'Limpieza con solvente dieléctrico y recalibración', includedInAgency: true, includedInPremium: true },
      ],
      remisionItems: [
        {
          id: 'rem-1',
          quantity: 5,
          unit: 'lts',
          description: 'Aceite de Motor 100% Sintético 5W-30',
          agencyBrand: 'KIA Original 5W-30 Full Synthetic',
          agencyUnitPrice: 240,
          agencyTotal: 1200,
          premiumBrand: 'Motul 8100 X-cess 5W-30 Sintético',
          premiumUnitPrice: 280,
          premiumTotal: 1400,
        },
        {
          id: 'rem-2',
          quantity: 4,
          unit: 'pzas',
          description: 'Juego de 4 Bujías de Iridio / Platino',
          agencyBrand: 'Bujías Genuinas KIA Mobis',
          agencyUnitPrice: 260,
          agencyTotal: 1040,
          premiumBrand: 'NGK Laser Iridium Long-Life (0.8mm)',
          premiumUnitPrice: 320,
          premiumTotal: 1280,
        },
        {
          id: 'rem-3',
          quantity: 1,
          unit: 'pza',
          description: 'Filtro de Aceite de Motor Blindado',
          agencyBrand: 'OEM KIA 26300-35505',
          agencyUnitPrice: 220,
          agencyTotal: 220,
          premiumBrand: 'Mann Filter Pro W712/83',
          premiumUnitPrice: 260,
          premiumTotal: 260,
        },
        {
          id: 'rem-4',
          quantity: 1,
          unit: 'pza',
          description: 'Filtro de Aire de Motor',
          agencyBrand: 'OEM KIA 28113-F2000',
          agencyUnitPrice: 380,
          agencyTotal: 380,
          premiumBrand: 'Mann Filter C30005',
          premiumUnitPrice: 420,
          premiumTotal: 420,
        },
        {
          id: 'rem-5',
          quantity: 1,
          unit: 'pza',
          description: 'Filtro de Cabina / Polen con Carbón Activado',
          agencyBrand: 'OEM KIA 97133-F2000',
          agencyUnitPrice: 290,
          agencyTotal: 290,
          premiumBrand: 'Mann Filter CUK 24013 FreciousPlus',
          premiumUnitPrice: 390,
          premiumTotal: 390,
        },
        {
          id: 'rem-6',
          quantity: 1,
          unit: 'serv',
          description: 'Descarbonizado de Inyectores & Cuerpo TPS',
          agencyBrand: 'Limpieza preventiva con aditivo',
          agencyUnitPrice: 350,
          agencyTotal: 350,
          premiumBrand: 'Limpieza ultrasónica y calibración OBD-II',
          premiumUnitPrice: 480,
          premiumTotal: 480,
        },
      ],
    },
    status: 'confirmada',
    scheduledDate: '2026-08-24',
    timeSlot: '15:30 - 18:00',
    technicianName: 'Luis González',
    technicianPhone: '3334884592',
    paymentMethod: 'online_card',
    paymentStatus: 'pending',
    cancellationPolicyAccepted: true,
    serviceRecord: {
      id: 'rec-1787603395427',
      appointmentId: 'apt-1787603395427',
      initialKm: 42350,
      evidencePhotos: [],
      installedParts: [
        { id: 'rem-1', name: 'Aceite de Motor 100% Sintético 5W-30 (5L)', brand: 'Motul 8100 X-cess', installed: true },
        { id: 'rem-2', name: '4x Bujías NGK Laser Iridium', brand: 'NGK Laser Iridium (0.8mm)', installed: true },
        { id: 'rem-3', name: 'Filtro de Aceite Blindado', brand: 'Mann Filter Pro W712', installed: true },
        { id: 'rem-4', name: 'Filtro de Aire Motor', brand: 'Mann Filter C30005', installed: true },
        { id: 'rem-5', name: 'Filtro de Cabina Carbón', brand: 'Mann Filter CUK 24013', installed: true },
        { id: 'rem-6', name: 'Descarbonizado de Inyectores & Cuerpo TPS', brand: 'Ultrasonido & Scanner', installed: true },
      ],
      mechanicalObservations: 'Servicio de afinación mayor a domicilio con refacciones de autor.',
      futureRecommendations: 'Próxima afinación en 10,000 km o 6 meses para conservar garantía.',
    },
    createdAt: '2026-08-24T17:00:00.000Z',
  },

  // 2. CITA APROBADA POR CLIENTE (Dra. Sofía Villalobos)
  {
    id: 'apt-1787603395428',
    folio: 'ADA-2026-112',
    client: {
      name: 'Dra. Sofía Villalobos Ruiz',
      phone: '3312456789',
      email: 'sofia.villalobos@medicina.udg.mx',
      address: 'Av. Providencia 2450, Col. Providencia, Guadalajara',
      referenceNotes: 'Consultorio médico piso 3, estacionamiento para el taller móvil',
    },
    vehicle: {
      brand: 'Mazda',
      model: 'CX-5',
      year: 2022,
      plates: 'JPS-882-A',
      vin: 'JM3KFBDM8N0184729',
      engine: '2.5L Skyactiv-G 4 Cilindros',
      currentKm: 38900,
    },
    packageType: 'mayor',
    serviceDescription: 'Afinación Mayor Skyactiv con Aceite 0W-20 y Bujías Iridio',
    selectedOption: 'premium',
    quote: {
      agency: {
        title: 'Opción Agencia (Mazda OEM)',
        description: 'Refacciones genuinas de concesionaria Mazda.',
        partsBrand: 'Genuino Mazda OEM',
        warrantyMonths: 6,
        laborCost: 650,
        partsSubtotal: 2800,
        price: 3450,
        highlights: [
          'Aceite genuino Mazda Moly 0W-20',
          'Garantía de 6 meses por escrito',
          'Escaneo computarizado Skyactiv',
        ],
      },
      premium: {
        title: 'Opción De Autor (Alto Rendimiento)',
        description: 'Motul 8100 Eco-lite 0W-20, Bujías NGK Laser Iridium y Filtro Mann Pro.',
        partsBrand: 'Motul 8100 0W-20 + NGK Laser Iridium + Mann Filter',
        warrantyMonths: 12,
        laborCost: 650,
        partsSubtotal: 3350,
        price: 4000,
        highlights: [
          'Máxima protección para motor Skyactiv de inyección directa',
          'Póliza de garantía extendida de 12 meses / 15,000 km',
          'Descarbonizado ultrasónico de inyectores en sitio',
        ],
      },
      itemsChecklist: [
        { name: 'Aceite Motul 8100 Eco-lite 0W-20 (5L)', spec: '100% Sintético Skyactiv', includedInAgency: true, includedInPremium: true },
        { name: '4x Bujías NGK Laser Iridium Skyactiv', spec: 'Calibradas a 0.8mm', includedInAgency: true, includedInPremium: true },
        { name: 'Filtro de Aceite Mann Filter W67/1', spec: 'Antidrenaje y sellado térmico', includedInAgency: true, includedInPremium: true },
        { name: 'Filtro de Aire Mann Filter C27019', spec: 'Microfiltración de alto flujo', includedInAgency: true, includedInPremium: true },
        { name: 'Filtro de Cabina Mann Filter CU2043', spec: 'Carbón activado anti-alérgenos', includedInAgency: true, includedInPremium: true },
        { name: 'Descarbonizado Inyectores GDI & Cuerpo TPS', spec: 'Limpieza ultrasónica con scanner', includedInAgency: true, includedInPremium: true },
      ],
      remisionItems: [
        {
          id: 'rem-m1',
          quantity: 5,
          unit: 'lts',
          description: 'Aceite de Motor 100% Sintético 0W-20 Skyactiv',
          agencyBrand: 'Mazda Genuine Oil 0W-20',
          agencyUnitPrice: 260,
          agencyTotal: 1300,
          premiumBrand: 'Motul 8100 Eco-lite 0W-20 Dexos1',
          premiumUnitPrice: 310,
          premiumTotal: 1550,
        },
        {
          id: 'rem-m2',
          quantity: 4,
          unit: 'pzas',
          description: 'Juego de 4 Bujías de Iridio Skyactiv High-Ignition',
          agencyBrand: 'Bujías Originales Mazda PE5R-18-110',
          agencyUnitPrice: 290,
          agencyTotal: 1160,
          premiumBrand: 'NGK Laser Iridium ILKAR7L11',
          premiumUnitPrice: 340,
          premiumTotal: 1360,
        },
        {
          id: 'rem-m3',
          quantity: 1,
          unit: 'pza',
          description: 'Filtro de Aceite de Motor Blindado',
          agencyBrand: 'OEM Mazda 1WPE-14-302',
          agencyUnitPrice: 230,
          agencyTotal: 230,
          premiumBrand: 'Mann Filter W67/1',
          premiumUnitPrice: 270,
          premiumTotal: 270,
        },
        {
          id: 'rem-m4',
          quantity: 1,
          unit: 'pza',
          description: 'Filtro de Aire de Motor',
          agencyBrand: 'OEM Mazda PE07-13-3A0A',
          agencyUnitPrice: 390,
          agencyTotal: 390,
          premiumBrand: 'Mann Filter C27019 Pro',
          premiumUnitPrice: 430,
          premiumTotal: 430,
        },
        {
          id: 'rem-m5',
          quantity: 1,
          unit: 'pza',
          description: 'Filtro de Cabina / Polen con Carbón Activado',
          agencyBrand: 'OEM Mazda KD45-61-J6X',
          agencyUnitPrice: 310,
          agencyTotal: 310,
          premiumBrand: 'Mann Filter CU2043 Carbón',
          premiumUnitPrice: 410,
          premiumTotal: 410,
        },
      ],
    },
    status: 'aprobada_por_cliente',
    scheduledDate: '2026-08-25',
    timeSlot: '09:00 - 11:30',
    technicianName: 'Luis Carlos Carranza',
    technicianPhone: '3334884592',
    paymentMethod: 'online_card',
    paymentStatus: 'pending',
    cancellationPolicyAccepted: true,
    createdAt: '2026-08-24T16:20:00.000Z',
  },

  // 3. COTIZACIÓN ENVIADA AL CLIENTE (Ing. Roberto Morales)
  {
    id: 'apt-1787603395429',
    folio: 'ADA-2026-108',
    client: {
      name: 'Ing. Roberto Morales Cárdenas',
      phone: '3323456781',
      email: 'roberto.morales@techgdl.com',
      address: 'Paseo de las Aves 430, Col. Valle Real, Zapopan',
      referenceNotes: 'Casa club privada, acceso con código de guardia',
    },
    vehicle: {
      brand: 'Volkswagen',
      model: 'Jetta',
      year: 2021,
      plates: 'JJH-901-B',
      vin: '3VW2K7AJ8MM091823',
      engine: '1.4L TSI Turbo 4 Cilindros',
      currentKm: 51200,
    },
    packageType: 'mayor',
    serviceDescription: 'Afinación Mayor TSI Turbo con Aceite Sintético VW 502.00',
    quote: {
      agency: {
        title: 'Opción Agencia (VW OEM)',
        description: 'Refacciones originales de concesionaria Volkswagen.',
        partsBrand: 'Genuino VW OEM',
        warrantyMonths: 6,
        laborCost: 650,
        partsSubtotal: 2950,
        price: 3600,
        highlights: [
          'Aceite genuino VW LongLife III 5W-40',
          'Póliza de garantía de 6 meses',
          'Diagnóstico VAG-COM oficial en domicilio',
        ],
      },
      premium: {
        title: 'Opción De Autor (Alto Rendimiento)',
        description: 'Motul 8100 X-clean 5W-40 (Norma VW 502 00/505 00), Bujías NGK Laser Platinum y Filtros Mann.',
        partsBrand: 'Motul 8100 X-clean + NGK Laser Platinum + Mann Filter',
        warrantyMonths: 12,
        laborCost: 650,
        partsSubtotal: 3450,
        price: 4100,
        highlights: [
          'Fórmula 100% sintética para turbocargadores de alta temperatura',
          'Garantía por escrito de 12 meses / 15,000 km',
          'Descarbonización de cuerpo de aceleración y recalibración VAG',
        ],
      },
      itemsChecklist: [
        { name: 'Aceite Motul 8100 X-clean 5W-40 (5L)', spec: 'Norma Oficial VW 502.00 / 505.00', includedInAgency: true, includedInPremium: true },
        { name: '4x Bujías NGK Laser Platinum TSI', spec: 'Calibradas para motor turbo', includedInAgency: true, includedInPremium: true },
        { name: 'Filtro de Aceite Mann Filter W712/95', spec: 'Válvula antidrenaje de alta presión', includedInAgency: true, includedInPremium: true },
        { name: 'Filtro de Aire Mann Filter C27009', spec: 'Elemento filtrante de celulosa sintética', includedInAgency: true, includedInPremium: true },
        { name: 'Filtro de Cabina Mann Filter FP26009', spec: 'Antialérgico con polifenol y carbón', includedInAgency: true, includedInPremium: true },
      ],
      remisionItems: [
        {
          id: 'rem-vw1',
          quantity: 5,
          unit: 'lts',
          description: 'Aceite de Motor 100% Sintético 5W-40 VW 502.00',
          agencyBrand: 'Volkswagen LongLife 5W-40',
          agencyUnitPrice: 270,
          agencyTotal: 1350,
          premiumBrand: 'Motul 8100 X-clean 5W-40',
          premiumUnitPrice: 320,
          premiumTotal: 1600,
        },
        {
          id: 'rem-vw2',
          quantity: 4,
          unit: 'pzas',
          description: 'Juego de 4 Bujías para Motor TSI Turbo',
          agencyBrand: 'OEM VW 04E-905-601-B',
          agencyUnitPrice: 310,
          agencyTotal: 1240,
          premiumBrand: 'NGK Laser Platinum PZKER7A8EGS',
          premiumUnitPrice: 360,
          premiumTotal: 1440,
        },
        {
          id: 'rem-vw3',
          quantity: 1,
          unit: 'pza',
          description: 'Filtro de Aceite Blindado TSI',
          agencyBrand: 'OEM VW 04E-115-561-H',
          agencyUnitPrice: 240,
          agencyTotal: 240,
          premiumBrand: 'Mann Filter W712/95',
          premiumUnitPrice: 280,
          premiumTotal: 280,
        },
      ],
    },
    status: 'cotizado',
    scheduledDate: '2026-08-26',
    timeSlot: '12:00 - 14:30',
    technicianName: 'Carlos Carranza',
    technicianPhone: '3334884592',
    paymentMethod: 'online_card',
    paymentStatus: 'pending',
    cancellationPolicyAccepted: false,
    createdAt: '2026-08-24T15:10:00.000Z',
  },

  // 4. SOLICITUD PENDIENTE DE COTIZAR (Arq. Mariana Herrera)
  {
    id: 'apt-1787603395430',
    folio: 'ADA-2026-097',
    client: {
      name: 'Arq. Mariana Herrera Lozano',
      phone: '3338901234',
      email: 'mariana.herrera@estudioarq.com',
      address: 'Av. Acueducto 6050, Col. Puerta de Hierro, Zapopan',
      referenceNotes: 'Torre corporativa nivel 12',
    },
    vehicle: {
      brand: 'Honda',
      model: 'CR-V',
      year: 2020,
      plates: 'JKM-314-C',
      vin: '3CZRU5854LM719024',
      engine: '1.5L VTEC Turbo 4 Cilindros',
      currentKm: 64000,
    },
    packageType: 'mayor',
    serviceDescription: 'Afinación Mayor VTEC Turbo a Domicilio',
    status: 'solicitud_pendiente',
    scheduledDate: '2026-08-27',
    timeSlot: '09:00 - 11:30',
    technicianName: 'Luis González',
    technicianPhone: '3334884592',
    paymentMethod: 'online_card',
    paymentStatus: 'pending',
    cancellationPolicyAccepted: false,
    createdAt: '2026-08-24T14:40:00.000Z',
  },

  // 5. SERVICIO CONCLUIDO CON PÓLIZA DE GARANTÍA (Lic. Fernando Castañeda)
  {
    id: 'apt-1787603395431',
    folio: 'ADA-2026-084',
    client: {
      name: 'Lic. Fernando Castañeda Soto',
      phone: '3315678901',
      email: 'fernando.castaneda@notaria44.mx',
      address: 'Av. Chapultepec Sur 380, Col. Americana, Guadalajara',
      referenceNotes: 'Notaría 44, recepción planta baja',
    },
    vehicle: {
      brand: 'Nissan',
      model: 'Versa',
      year: 2022,
      plates: 'JLL-552-D',
      vin: '3N1CN8EV0NL847291',
      engine: '1.6L HR16DE 4 Cilindros',
      currentKm: 48500,
    },
    packageType: 'mayor',
    serviceDescription: 'Afinación Mayor de Alto Rendimiento a Domicilio',
    selectedOption: 'premium',
    quote: {
      agency: {
        title: 'Opción Agencia (Nissan OEM)',
        description: 'Refacciones genuinas de concesionaria Nissan.',
        partsBrand: 'Genuino Nissan OEM',
        warrantyMonths: 6,
        laborCost: 650,
        partsSubtotal: 2400,
        price: 3050,
        highlights: ['Refacciones oficiales Nissan', 'Garantía 6 meses'],
      },
      premium: {
        title: 'Opción De Autor (Alto Rendimiento)',
        description: 'Motul 8100 5W-30, NGK Laser Iridium y Filtros Mann.',
        partsBrand: 'Motul 8100 + NGK Laser Iridium + Mann Filter',
        warrantyMonths: 12,
        laborCost: 650,
        partsSubtotal: 2900,
        price: 3550,
        highlights: ['Garantía 12 meses por escrito', 'Ultrasonido y escaneo OBD-II'],
      },
      itemsChecklist: [
        { name: 'Aceite Motul 8100 5W-30 (5L)', spec: '100% Sintético', includedInAgency: true, includedInPremium: true },
        { name: '4x Bujías NGK Laser Iridium DILKAR6A11', spec: 'Calibradas a 1.1mm', includedInAgency: true, includedInPremium: true },
        { name: 'Filtro de Aceite Mann Filter W67/1', spec: 'Blindado', includedInAgency: true, includedInPremium: true },
        { name: 'Filtro de Aire Mann Filter C24059', spec: 'Microfiltración', includedInAgency: true, includedInPremium: true },
        { name: 'Filtro de Cabina Mann Filter CU21003', spec: 'Carbón activado', includedInAgency: true, includedInPremium: true },
      ],
    },
    status: 'completada',
    scheduledDate: '2026-08-20',
    timeSlot: '10:00 - 12:30',
    technicianName: 'Carlos Carranza',
    technicianPhone: '3334884592',
    paymentMethod: 'online_card',
    paymentStatus: 'paid',
    cancellationPolicyAccepted: true,
    serviceRecord: {
      id: 'rec-1787603395431',
      appointmentId: 'apt-1787603395431',
      arrivalTime: '10:05',
      startedAt: '2026-08-20T10:10:00.000Z',
      completedAt: '2026-08-20T11:45:00.000Z',
      initialKm: 48500,
      evidencePhotos: [
        {
          id: 'ev-done-1',
          category: 'bujias',
          label: 'Bujías de Encendido',
          beforePhotoUrl: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&auto=format&fit=crop&q=60',
          afterPhotoUrl: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=800&auto=format&fit=crop&q=60',
          notes: 'Bujías anteriores gastadas a 1.3mm. Instaladas 4 bujías NGK Laser Iridium calibradas a 1.1mm.',
        },
        {
          id: 'ev-done-2',
          category: 'aceite',
          label: 'Aceite de Motor & Filtro',
          beforePhotoUrl: 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=800&auto=format&fit=crop&q=60',
          afterPhotoUrl: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=800&auto=format&fit=crop&q=60',
          notes: 'Aceite negro degradado drenado. Relleno con Motul 8100 100% sintético y filtro blindado nuevo.',
        },
      ],
      installedParts: [
        { id: 'done-p1', name: '4x Bujías NGK Laser Iridium DILKAR6A11', brand: 'NGK Laser Iridium', installed: true },
        { id: 'done-p2', name: 'Aceite Motul 8100 X-cess 5W-30 (5L)', brand: 'Motul 100% Sintético', installed: true },
        { id: 'done-p3', name: 'Filtro de Aceite Blindado Mann Filter', brand: 'Mann Filter Pro', installed: true },
        { id: 'done-p4', name: 'Filtro de Aire de Motor Mann Filter', brand: 'Mann Filter Pro', installed: true },
        { id: 'done-p5', name: 'Filtro de Cabina Carbón Activado', brand: 'Mann Filter CUK', installed: true },
      ],
      mechanicalObservations: 'Servicio de afinación mayor concluido al 100%. Escaneo OBD-II sin códigos de falla activos. Motor sereno y aceleración óptima.',
      futureRecommendations: 'Realizar siguiente servicio semestral preventivo a los 58,500 km o en 6 meses para mantener la garantía vigente.',
      clientSignatureUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="320" height="120" viewBox="0 0 320 120"><rect width="320" height="120" fill="%23F8FAFC" rx="10"/><path d="M 30 70 Q 70 30 110 65 T 190 60 T 270 50" fill="none" stroke="%2308101E" stroke-width="3" stroke-linecap="round"/><text x="30" y="95" font-family="sans-serif" font-size="12" font-weight="bold" fill="%2308101E">Lic. Fernando Castañeda Soto</text><text x="30" y="110" font-family="sans-serif" font-size="9" fill="%23666666">Firma Digital Certificada • Afinaciones de Autor</text></svg>',
      signedByName: 'Lic. Fernando Castañeda Soto',
    },
    nextFollowUpDate: '2027-02-20',
    followUpStatus: 'pending',
    createdAt: '2026-08-20T09:00:00.000Z',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationLog[] = [
  {
    id: 'notif-1',
    appointmentId: 'apt-1787603395427',
    channel: 'whatsapp',
    type: 'booking_confirmed',
    recipient: '3334884592',
    title: '✅ Cita Confirmada: 24-08-2026 (15:30 - 18:00)',
    message: 'Hola Emilio González García! Tu cita para KIA Soul ha quedado confirmada. Técnico: Luis González.',
    timestamp: '2026-08-24T17:05:00.000Z',
  },
  {
    id: 'notif-2',
    appointmentId: 'apt-1787603395428',
    channel: 'whatsapp',
    type: 'quote_sent',
    recipient: '3312456789',
    title: '📋 Propuesta Autorizada por el Cliente',
    message: 'Dra. Sofía Villalobos autorizó la propuesta De Autor (Alto Rendimiento) para su Mazda CX-5.',
    timestamp: '2026-08-24T16:25:00.000Z',
  },
  {
    id: 'notif-3',
    appointmentId: 'apt-1787603395431',
    channel: 'email',
    type: 'service_completed_pdf',
    recipient: 'fernando.castaneda@notaria44.mx',
    title: '🎉 Póliza de Garantía Emitida (12 Meses)',
    message: 'Reporte Técnico digital y certificado de garantía emitido para Nissan Versa.',
    timestamp: '2026-08-20T11:50:00.000Z',
  },
];
