import { Appointment, NotificationLog, BusinessScheduleSettings, SecuritySettings } from '@/types';

/**
 * Base de datos de Afinaciones de Autor con las cotizaciones de prueba de los clientes del usuario.
 */

export const INITIAL_SECURITY_SETTINGS: SecuritySettings = {
  adminPin: '123456',
  technicianPin: '123456',
  staffMembers: [
    {
      id: 'staff-1',
      name: 'Luis Carlos Carranza',
      phone: '3334884592',
      role: 'admin',
      status: 'active',
      pin: '123456',
      createdAt: '2026-08-24T10:00:00.000Z',
    },
    {
      id: 'staff-2',
      name: 'Luis González',
      phone: '3334884592',
      role: 'technician',
      status: 'active',
      pin: '123456',
      createdAt: '2026-08-24T10:00:00.000Z',
    },
    {
      id: 'staff-3',
      name: 'Carlos Carranza',
      phone: '3334884592',
      role: 'technician',
      status: 'active',
      pin: '123456',
      createdAt: '2026-08-24T10:00:00.000Z',
    },
  ],
};

export const INITIAL_SCHEDULE_SETTINGS: BusinessScheduleSettings = {
  workingDays: [
    { dayOfWeek: 1, name: 'Lunes', enabled: true },
    { dayOfWeek: 2, name: 'Martes', enabled: true },
    { dayOfWeek: 3, name: 'Miércoles', enabled: true },
    { dayOfWeek: 4, name: 'Jueves', enabled: true },
    { dayOfWeek: 5, name: 'Viernes', enabled: true },
    { dayOfWeek: 6, name: 'Sábado', enabled: true },
    { dayOfWeek: 0, name: 'Domingo', enabled: true },
  ],
  slots: [
    { id: 'slot-1', slot: '09:00 - 11:30', label: 'Mañana (Recomendado)', active: true },
    { id: 'slot-2', slot: '12:00 - 14:30', label: 'Mediodía', active: true },
    { id: 'slot-3', slot: '15:30 - 18:00', label: 'Tarde', active: true },
    { id: 'slot-4', slot: '18:30 - 20:30', label: 'Vespertino', active: true },
  ],
  blockedDates: [],
};

export const INITIAL_APPOINTMENTS: Appointment[] = [
  // 1. EMILIO GONZÁLEZ GARCÍA (Confirmada)
  {
    id: 'apt-1787603395427',
    folio: 'ADA-2026-115',
    client: {
      name: 'Emilio González García',
      phone: '3334884592',
      email: 'emilio.gonzalez@gmail.com',
      address: 'Santa Monica 128 Nueva Santa Maria, Guadalajara',
      referenceNotes: 'Portón gris frente al parque',
    },
    vehicle: {
      brand: 'KIA',
      model: 'Soul',
      year: 2023,
      plates: 'DSS-421-5',
      vin: 'KNDJP3A56N7129845',
      engine: '2.0L MPI 4 Cilindros',
      currentKm: 42350,
    },
    packageType: 'mayor',
    serviceDescription: 'Afinación Mayor de Alto Rendimiento a Domicilio',
    selectedOption: 'premium',
    quote: {
      agency: {
        title: 'Opción Agencia (KIA OEM)',
        description: 'Refacciones 100% de concesionaria autorizada KIA.',
        partsBrand: 'Genuino KIA OEM',
        warrantyMonths: 6,
        laborCost: 650,
        partsSubtotal: 2650,
        price: 3300,
        highlights: [
          'Refacciones 100% de concesionaria oficial',
          'Póliza de garantía legal de 6 meses',
          'Inspección y escaneo digital en tu domicilio',
        ],
      },
      premium: {
        title: 'Opción De Autor (Alto Rendimiento)',
        description: 'Refacciones de especificación superior (Motul 8100 100% Sintético, NGK Laser Iridium, Mann Filter Pro).',
        partsBrand: 'Motul 8100 + NGK Laser Iridium + Mann Filter Pro',
        warrantyMonths: 12,
        laborCost: 650,
        partsSubtotal: 3100,
        price: 3750,
        highlights: [
          'Marcas premium de máximo desempeño y durabilidad',
          'Garantía extendida por escrito de 12 meses / 15,000 km',
          'Descarbonización ultrasónica y calibración con escáner OBD-II',
        ],
      },
      itemsChecklist: [
        { name: '4x Bujías NGK Laser Iridium', spec: 'Calibración GAP 0.8mm', includedInAgency: true, includedInPremium: true },
        { name: 'Aceite Motul 8100 100% Sintético 5W-30 (5L)', spec: 'API SP / ILSAC GF-6A', includedInAgency: true, includedInPremium: true },
        { name: 'Filtro de Aceite Mann Filter W712', spec: 'Válvula antidrenaje blindada', includedInAgency: true, includedInPremium: true },
        { name: 'Filtro de Aire Mann Filter C30005', spec: 'Microfiltración de alto flujo', includedInAgency: true, includedInPremium: true },
        { name: 'Filtro de Cabina Mann Filter CUK', spec: 'Carbón activado anti-alérgenos', includedInAgency: true, includedInPremium: true },
        { name: 'Descarbonizado de Inyectores & Cuerpo TPS', spec: 'Limpieza con solvente dieléctrico y recalibración', includedInAgency: true, includedInPremium: true },
      ],
      remisionItems: [
        {
          id: 'rem-1',
          quantity: 5,
          unit: 'lts',
          description: 'Aceite de Motor 100% Sintético 5W-30',
          agencyBrand: 'KIA Original 5W-30 Full Synthetic',
          agencyUnitPrice: 240,
          agencyTotal: 1200,
          premiumBrand: 'Motul 8100 X-cess 5W-30 Sintético',
          premiumUnitPrice: 280,
          premiumTotal: 1400,
        },
        {
          id: 'rem-2',
          quantity: 4,
          unit: 'pzas',
          description: 'Juego de 4 Bujías de Iridio / Platino',
          agencyBrand: 'Bujías Genuinas KIA Mobis',
          agencyUnitPrice: 260,
          agencyTotal: 1040,
          premiumBrand: 'NGK Laser Iridium Long-Life (0.8mm)',
          premiumUnitPrice: 320,
          premiumTotal: 1280,
        },
        {
          id: 'rem-3',
          quantity: 1,
          unit: 'pza',
          description: 'Filtro de Aceite de Motor Blindado',
          agencyBrand: 'OEM KIA 26300-35505',
          agencyUnitPrice: 220,
          agencyTotal: 220,
          premiumBrand: 'Mann Filter Pro W712/83',
          premiumUnitPrice: 260,
          premiumTotal: 260,
        },
        {
          id: 'rem-4',
          quantity: 1,
          unit: 'pza',
          description: 'Filtro de Aire de Motor',
          agencyBrand: 'OEM KIA 28113-F2000',
          agencyUnitPrice: 380,
          agencyTotal: 380,
          premiumBrand: 'Mann Filter C30005',
          premiumUnitPrice: 420,
          premiumTotal: 420,
        },
        {
          id: 'rem-5',
          quantity: 1,
          unit: 'pza',
          description: 'Filtro de Cabina / Polen con Carbón Activado',
          agencyBrand: 'OEM KIA 97133-F2000',
          agencyUnitPrice: 290,
          agencyTotal: 290,
          premiumBrand: 'Mann Filter CUK 24013 FreciousPlus',
          premiumUnitPrice: 390,
          premiumTotal: 390,
        },
        {
          id: 'rem-6',
          quantity: 1,
          unit: 'serv',
          description: 'Descarbonizado de Inyectores & Cuerpo TPS',
          agencyBrand: 'Limpieza preventiva con aditivo',
          agencyUnitPrice: 350,
          agencyTotal: 350,
          premiumBrand: 'Limpieza ultrasónica y calibración OBD-II',
          premiumUnitPrice: 480,
          premiumTotal: 480,
        },
      ],
    },
    status: 'confirmada',
    scheduledDate: '2026-08-24',
    timeSlot: '15:30 - 18:00',
    technicianName: 'Luis González',
    technicianPhone: '3334884592',
    paymentMethod: 'online_card',
    paymentStatus: 'pending',
    cancellationPolicyAccepted: true,
    serviceRecord: {
      id: 'rec-1787603395427',
      appointmentId: 'apt-1787603395427',
      initialKm: 42350,
      evidencePhotos: [],
      installedParts: [
        { id: 'rem-1', name: 'Aceite de Motor 100% Sintético 5W-30 (5L)', brand: 'Motul 8100 X-cess', installed: true },
        { id: 'rem-2', name: '4x Bujías NGK Laser Iridium', brand: 'NGK Laser Iridium (0.8mm)', installed: true },
        { id: 'rem-3', name: 'Filtro de Aceite Blindado', brand: 'Mann Filter Pro W712', installed: true },
        { id: 'rem-4', name: 'Filtro de Aire Motor', brand: 'Mann Filter C30005', installed: true },
        { id: 'rem-5', name: 'Filtro de Cabina Carbón', brand: 'Mann Filter CUK 24013', installed: true },
        { id: 'rem-6', name: 'Descarbonizado de Inyectores & Cuerpo TPS', brand: 'Ultrasonido & Scanner', installed: true },
      ],
      mechanicalObservations: 'Servicio de afinación mayor a domicilio con refacciones de autor.',
      futureRecommendations: 'Próxima afinación en 10,000 km o 6 meses para conservar garantía.',
    },
    createdAt: '2026-08-24T17:00:00.000Z',
  },

  // 2. ISAAC (Aprobada / Confirmada)
  {
    id: 'apt-isaac-' + Date.now(),
    folio: 'ADA-2026-116',
    client: {
      name: 'Isaac',
      phone: '3334884592',
      email: 'isaac@example.com',
      address: 'Guadalajara, Jalisco',
      referenceNotes: 'Cita de prueba registrada',
    },
    vehicle: {
      brand: 'Nissan',
      model: 'Versa',
      year: 2022,
      plates: 'JLL-552-D',
      vin: '3N1CN8EV0NL847291',
      engine: '1.6L 4 Cilindros',
      currentKm: 35000,
    },
    packageType: 'mayor',
    serviceDescription: 'Afinación Mayor de Alto Rendimiento',
    selectedOption: 'premium',
    quote: {
      agency: {
        title: 'Opción Agencia (Nissan OEM)',
        description: 'Refacciones de concesionaria autorizada Nissan.',
        partsBrand: 'Genuino Nissan OEM',
        warrantyMonths: 6,
        laborCost: 650,
        partsSubtotal: 2400,
        price: 3050,
        highlights: ['Refacciones oficiales', 'Garantía 6 meses'],
      },
      premium: {
        title: 'Opción De Autor (Alto Rendimiento)',
        description: 'Motul 8100 5W-30, NGK Laser Iridium y Mann Filter.',
        partsBrand: 'Motul 8100 + NGK Laser Iridium + Mann Filter',
        warrantyMonths: 12,
        laborCost: 650,
        partsSubtotal: 2900,
        price: 3550,
        highlights: ['Garantía 12 meses por escrito', 'Ultrasonido y escaneo OBD-II'],
      },
      itemsChecklist: [
        { name: 'Aceite Motul 8100 5W-30 (5L)', spec: '100% Sintético', includedInAgency: true, includedInPremium: true },
        { name: '4x Bujías NGK Laser Iridium', spec: 'Calibración a manual', includedInAgency: true, includedInPremium: true },
        { name: 'Filtro de Aceite Mann Filter', spec: 'Blindado', includedInAgency: true, includedInPremium: true },
        { name: 'Filtro de Aire Mann Filter', spec: 'Microfiltración', includedInAgency: true, includedInPremium: true },
        { name: 'Filtro de Cabina Carbón Activado', spec: 'Antialérgico', includedInAgency: true, includedInPremium: true },
      ],
      remisionItems: [
        {
          id: 'rem-is-1',
          quantity: 5,
          unit: 'lts',
          description: 'Aceite de Motor 100% Sintético 5W-30',
          agencyBrand: 'Nissan Original 5W-30',
          agencyUnitPrice: 220,
          agencyTotal: 1100,
          premiumBrand: 'Motul 8100 X-cess 5W-30',
          premiumUnitPrice: 280,
          premiumTotal: 1400,
        },
        {
          id: 'rem-is-2',
          quantity: 4,
          unit: 'pzas',
          description: 'Juego de 4 Bujías de Iridio',
          agencyBrand: 'Bujías Originales Nissan',
          agencyUnitPrice: 250,
          agencyTotal: 1000,
          premiumBrand: 'NGK Laser Iridium DILKAR6A11',
          premiumUnitPrice: 310,
          premiumTotal: 1240,
        },
        {
          id: 'rem-is-3',
          quantity: 1,
          unit: 'pza',
          description: 'Filtro de Aceite de Motor Blindado',
          agencyBrand: 'OEM Nissan 15208-65F0A',
          agencyUnitPrice: 180,
          agencyTotal: 180,
          premiumBrand: 'Mann Filter W67/1',
          premiumUnitPrice: 220,
          premiumTotal: 220,
        },
        {
          id: 'rem-is-4',
          quantity: 1,
          unit: 'pza',
          description: 'Filtro de Aire de Motor',
          agencyBrand: 'OEM Nissan 16546-1HK0J',
          agencyUnitPrice: 320,
          agencyTotal: 320,
          premiumBrand: 'Mann Filter C24059',
          premiumUnitPrice: 380,
          premiumTotal: 380,
        },
      ],
    },
    status: 'confirmada',
    scheduledDate: '2026-08-24',
    timeSlot: '12:00 - 14:30',
    technicianName: 'Luis González',
    technicianPhone: '3334884592',
    paymentMethod: 'online_card',
    paymentStatus: 'pending',
    cancellationPolicyAccepted: true,
    createdAt: '2026-08-24T18:00:00.000Z',
  },

  // 3. PEDRO (Cotizada / Aprobada)
  {
    id: 'apt-pedro-' + Date.now(),
    folio: 'ADA-2026-117',
    client: {
      name: 'Pedro',
      phone: '3334884592',
      email: 'pedro@example.com',
      address: 'Zapopan, Jalisco',
      referenceNotes: 'Cita de prueba registrada',
    },
    vehicle: {
      brand: 'Volkswagen',
      model: 'Jetta',
      year: 2021,
      plates: 'JJH-901-B',
      vin: '3VW2K7AJ8MM091823',
      engine: '1.4L TSI Turbo',
      currentKm: 48000,
    },
    packageType: 'mayor',
    serviceDescription: 'Afinación Mayor TSI Turbo',
    selectedOption: 'premium',
    quote: {
      agency: {
        title: 'Opción Agencia (VW OEM)',
        description: 'Refacciones genuinas Volkswagen.',
        partsBrand: 'Genuino VW OEM',
        warrantyMonths: 6,
        laborCost: 650,
        partsSubtotal: 2800,
        price: 3450,
        highlights: ['Refacciones oficiales VW', 'Garantía 6 meses'],
      },
      premium: {
        title: 'Opción De Autor (Alto Rendimiento)',
        description: 'Motul 8100 X-clean 5W-40, NGK Laser Platinum y Mann Filter.',
        partsBrand: 'Motul 8100 + NGK Platinum + Mann Filter',
        warrantyMonths: 12,
        laborCost: 650,
        partsSubtotal: 3300,
        price: 3950,
        highlights: ['Garantía 12 meses', 'Descarbonizado ultrasónico'],
      },
      itemsChecklist: [
        { name: 'Aceite Motul 8100 5W-40 VW 502.00 (5L)', spec: '100% Sintético', includedInAgency: true, includedInPremium: true },
        { name: '4x Bujías NGK Laser Platinum', spec: 'TSI Turbo', includedInAgency: true, includedInPremium: true },
        { name: 'Filtro de Aceite Mann Filter W712/95', spec: 'Blindado', includedInAgency: true, includedInPremium: true },
        { name: 'Filtro de Aire Mann Filter C27009', spec: 'Microfiltración', includedInAgency: true, includedInPremium: true },
      ],
      remisionItems: [
        {
          id: 'rem-pe-1',
          quantity: 5,
          unit: 'lts',
          description: 'Aceite de Motor 100% Sintético 5W-40 VW 502.00',
          agencyBrand: 'VW LongLife 5W-40',
          agencyUnitPrice: 260,
          agencyTotal: 1300,
          premiumBrand: 'Motul 8100 X-clean 5W-40',
          premiumUnitPrice: 310,
          premiumTotal: 1550,
        },
        {
          id: 'rem-pe-2',
          quantity: 4,
          unit: 'pzas',
          description: 'Juego de 4 Bujías TSI Turbo',
          agencyBrand: 'OEM VW 04E-905-601-B',
          agencyUnitPrice: 290,
          agencyTotal: 1160,
          premiumBrand: 'NGK Laser Platinum PZKER7A8EGS',
          premiumUnitPrice: 340,
          premiumTotal: 1360,
        },
        {
          id: 'rem-pe-3',
          quantity: 1,
          unit: 'pza',
          description: 'Filtro de Aceite Blindado TSI',
          agencyBrand: 'OEM VW 04E-115-561-H',
          agencyUnitPrice: 220,
          agencyTotal: 220,
          premiumBrand: 'Mann Filter W712/95',
          premiumUnitPrice: 260,
          premiumTotal: 260,
        },
        {
          id: 'rem-pe-4',
          quantity: 1,
          unit: 'pza',
          description: 'Filtro de Aire de Motor',
          agencyBrand: 'OEM VW 04E-129-620',
          agencyUnitPrice: 360,
          agencyTotal: 360,
          premiumBrand: 'Mann Filter C27009',
          premiumUnitPrice: 400,
          premiumTotal: 400,
        },
      ],
    },
    status: 'confirmada',
    scheduledDate: '2026-08-24',
    timeSlot: '09:00 - 11:30',
    technicianName: 'Carlos Carranza',
    technicianPhone: '3334884592',
    paymentMethod: 'online_card',
    paymentStatus: 'pending',
    cancellationPolicyAccepted: true,
    createdAt: '2026-08-24T18:15:00.000Z',
  },

  // 4. JESÚS (Aprobada / Confirmada)
  {
    id: 'apt-jesus-' + Date.now(),
    folio: 'ADA-2026-118',
    client: {
      name: 'Jesús',
      phone: '3334884592',
      email: 'jesus@example.com',
      address: 'Guadalajara, Jalisco',
      referenceNotes: 'Cita de prueba registrada',
    },
    vehicle: {
      brand: 'Mazda',
      model: 'CX-5',
      year: 2022,
      plates: 'JPS-882-A',
      vin: 'JM3KFBDM8N0184729',
      engine: '2.5L Skyactiv',
      currentKm: 41000,
    },
    packageType: 'mayor',
    serviceDescription: 'Afinación Mayor Skyactiv 0W-20',
    selectedOption: 'premium',
    quote: {
      agency: {
        title: 'Opción Agencia (Mazda OEM)',
        description: 'Refacciones genuinas Mazda.',
        partsBrand: 'Genuino Mazda OEM',
        warrantyMonths: 6,
        laborCost: 650,
        partsSubtotal: 2700,
        price: 3350,
        highlights: ['Refacciones oficiales Mazda', 'Garantía 6 meses'],
      },
      premium: {
        title: 'Opción De Autor (Alto Rendimiento)',
        description: 'Motul 8100 0W-20, NGK Laser Iridium y Mann Filter.',
        partsBrand: 'Motul 8100 + NGK Laser Iridium + Mann Filter',
        warrantyMonths: 12,
        laborCost: 650,
        partsSubtotal: 3200,
        price: 3850,
        highlights: ['Garantía 12 meses', 'Descarbonizado ultrasónico'],
      },
      itemsChecklist: [
        { name: 'Aceite Motul 8100 Eco-lite 0W-20 (5L)', spec: '100% Sintético', includedInAgency: true, includedInPremium: true },
        { name: '4x Bujías NGK Laser Iridium Skyactiv', spec: 'Calibración a manual', includedInAgency: true, includedInPremium: true },
        { name: 'Filtro de Aceite Mann Filter W67/1', spec: 'Blindado', includedInAgency: true, includedInPremium: true },
        { name: 'Filtro de Aire Mann Filter C27019', spec: 'Microfiltración', includedInAgency: true, includedInPremium: true },
      ],
      remisionItems: [
        {
          id: 'rem-je-1',
          quantity: 5,
          unit: 'lts',
          description: 'Aceite de Motor 100% Sintético 0W-20 Skyactiv',
          agencyBrand: 'Mazda Oil 0W-20',
          agencyUnitPrice: 250,
          agencyTotal: 1250,
          premiumBrand: 'Motul 8100 Eco-lite 0W-20',
          premiumUnitPrice: 300,
          premiumTotal: 1500,
        },
        {
          id: 'rem-je-2',
          quantity: 4,
          unit: 'pzas',
          description: 'Juego de 4 Bujías Iridio Skyactiv',
          agencyBrand: 'OEM Mazda PE5R-18-110',
          agencyUnitPrice: 280,
          agencyTotal: 1120,
          premiumBrand: 'NGK Laser Iridium ILKAR7L11',
          premiumUnitPrice: 330,
          premiumTotal: 1320,
        },
        {
          id: 'rem-je-3',
          quantity: 1,
          unit: 'pza',
          description: 'Filtro de Aceite de Motor Blindado',
          agencyBrand: 'OEM Mazda 1WPE-14-302',
          agencyUnitPrice: 220,
          agencyTotal: 220,
          premiumBrand: 'Mann Filter W67/1',
          premiumUnitPrice: 250,
          premiumTotal: 250,
        },
        {
          id: 'rem-je-4',
          quantity: 1,
          unit: 'pza',
          description: 'Filtro de Aire de Motor',
          agencyBrand: 'OEM Mazda PE07-13-3A0A',
          agencyUnitPrice: 370,
          agencyTotal: 370,
          premiumBrand: 'Mann Filter C27019',
          premiumUnitPrice: 410,
          premiumTotal: 410,
        },
      ],
    },
    status: 'confirmada',
    scheduledDate: '2026-08-24',
    timeSlot: '15:30 - 18:00',
    technicianName: 'Luis González',
    technicianPhone: '3334884592',
    paymentMethod: 'online_card',
    paymentStatus: 'pending',
    cancellationPolicyAccepted: true,
    createdAt: '2026-08-24T18:30:00.000Z',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationLog[] = [
  {
    id: 'notif-1',
    appointmentId: 'apt-1787603395427',
    channel: 'whatsapp',
    type: 'booking_confirmed',
    recipient: '3334884592',
    title: '✅ Cita Confirmada: Emilio González García',
    message: 'Cita confirmada para KIA Soul (DSS-421-5). Técnico: Luis González.',
    timestamp: '2026-08-24T17:05:00.000Z',
  },
  {
    id: 'notif-2',
    appointmentId: 'apt-isaac',
    channel: 'whatsapp',
    type: 'booking_confirmed',
    recipient: '3334884592',
    title: '✅ Cita Confirmada: Isaac',
    message: 'Cita confirmada para Nissan Versa. Técnico: Luis González.',
    timestamp: '2026-08-24T18:05:00.000Z',
  },
  {
    id: 'notif-3',
    appointmentId: 'apt-pedro',
    channel: 'whatsapp',
    type: 'booking_confirmed',
    recipient: '3334884592',
    title: '✅ Cita Confirmada: Pedro',
    message: 'Cita confirmada para VW Jetta. Técnico: Carlos Carranza.',
    timestamp: '2026-08-24T18:20:00.000Z',
  },
  {
    id: 'notif-4',
    appointmentId: 'apt-jesus',
    channel: 'whatsapp',
    type: 'booking_confirmed',
    recipient: '3334884592',
    title: '✅ Cita Confirmada: Jesús',
    message: 'Cita confirmada para Mazda CX-5. Técnico: Luis González.',
    timestamp: '2026-08-24T18:35:00.000Z',
  },
];
